### ISSUE TITLE
orderingList: cannot init widget with functionality @contained

### ISSUE THREAD

**Issue by jstefek** [richwidgets/richwidgets#82] opened 2013-10-31 13:00 UTC
- open http://www.richwidgets.io/select/orderingList.html
- run in console 

```
$('#list').orderingList({contained: false});
```
- list item should be draggable outside of the list

But if you destroy it before, it works. 

```
$('#list').orderingList('destroy').orderingList({contained: false});
```

**Comment by bleathem** [comment] 2013-10-31 13:37
I must have missed that option in the `_setOption` method.  Nice catch.

**Comment by lfryc** [comment] 2013-11-02 16:06
This is duplicate of https://github.com/richwidgets/richwidgets/issues/80 as call of `$('#list').orderingList({contained: false});` effectively leads to calling `_setOption('contained', false);`.

**Closed as completed** 2013-11-02 16:07 UTC
Labels: orderingList, verified
