### ISSUE TITLE
orderingList: @showButtons cannot be reset after orderingList created

### ISSUE THREAD

**Issue by jstefek** [richwidgets/richwidgets#74] opened 2013-10-30 11:56 UTC
Can be reproduced by:
- open http://richwidgets.github.io/select/orderingList.html
- run in console 

```
$('#list').orderingList({showButtons: false});
```
- the buttons of the first orderingList should disappear (but they do not)

But when you recreate the ordering list, the buttons will disappear as expected: run this in console 

```
$('#list').orderingList('destroy').orderingList({showButtons: false});
```

 Is this an intention?

**Comment by lfryc** [comment] 2013-11-02 16:08
This is duplicate of #80 as call of `$('#list').orderingList({showButtons: false});` effectively leads to `_setOption('showButtons', false);`.

**Closed as completed by lfryc** 2013-11-02 16:08 UTC
Labels: orderingList, verified
